/*
 * WelcomePanel.java
 *
 * Created on 30 de junio de 2007, 05:57 PM
 */

package org.joing.desktop.login;

import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author  Mario Serrano
 */
public class WelcomePanel extends javax.swing.JPanel {
    
    private Image backgroundImage;
    
    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
        setBackgroundImage(getToolkit().createImage(getClass().getResource("/org/joing/desktop/login/resources/background.jpg")));     
     
    }
    
    @Override
protected void paintComponent(Graphics g) {
        g.drawImage(getBackgroundImage(), 0,0,getWidth(),getHeight(),this);
        
    }

    public Image getBackgroundImage() {
        return backgroundImage;
    }

    public void setBackgroundImage(Image backgroundImage) {
        this.backgroundImage = backgroundImage;
    }

    public org.joing.desktop.login.LoginPanel getLoginPanel() {
        return loginPanel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        loginPanel = new org.joing.desktop.login.LoginPanel();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(102, 102, 255));
        setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);
        jPanel1.add(loginPanel, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 20));
        add(jPanel2, java.awt.BorderLayout.PAGE_START);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.joing.desktop.login.LoginPanel loginPanel;
    // End of variables declaration//GEN-END:variables
    
    
}
