/*
 * LogPanel.java
 *
 * Created on 24 de junio de 2007, 17:16
 */

package org.joing.sysmon;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JPopupMenu;
import org.joing.common.clientAPI.log.Levels;
import org.joing.common.clientAPI.log.LogListener;
import org.joing.common.clientAPI.log.Logger;

/**
 * 
 * Note: This class has package scope, to be instantiated only by SystemMonitor.
 *
 * @author  Francisco Morero Peyrona
 */
class LogPanel extends javax.swing.JPanel implements LogListener
{
    private AbstractAction   actClear = null;
    private SimpleDateFormat sdf      = null;
    
    //------------------------------------------------------------------------//
    
    /** Creates new form LogPanel */
    LogPanel()
    {
        actClear = new ClearAction();
        
        initComponents();
        
        btnClear.setAction( actClear );
        
        JPopupMenu popup = new JPopupMenu();
                   popup.add( actClear );
        
        txtLog.setComponentPopupMenu( popup );
        clear();
        
        // Add AppManager Listener
        Logger logger = org.joing.common.clientAPI.log.SimpleLoggerFactory.getLogger( org.joing.common.clientAPI.log.JoingLogger.ID );
               logger.addListener( this );
    }
    
    public void clear()
    {
        txtLog.setText( "" );
    }
    
    //------------------------------------------------------------------------//
    // LogListener interface implementation
    
    public void write( Levels level, String msg )
    {
        addLine( level +" "+ msg );
    }
    
    //------------------------------------------------------------------------//
    
    private void addLine( String sLine )
    {
        if( sLine != null && sLine.length() > 0 )
        {
            StringBuffer sb = new StringBuffer();
            
            if( sdf == null )
            {
                sdf = new SimpleDateFormat( "[yyyy-MM-dd 'at' HH:mm:ss] " );
                actClear.setEnabled( true );
            }

            sb.append( sdf.format( new Date() ) );
            sb.append( sLine ).append( '\n' );
            txtLog.append( sb.toString() );
        }
    }
    
    //------------------------------------------------------------------------//
    // INNER CLASSES
    //------------------------------------------------------------------------//
    
    private class ClearAction extends AbstractAction
    {
        private ClearAction()
        {
            super( "Clear" );
            putValue( AbstractAction.SHORT_DESCRIPTION, "Clears text-area" );
        }
        
        public boolean isEnabled()
        {
            return true;
        }
        
        public void actionPerformed( ActionEvent ae )
        {
            LogPanel.this.clear();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTextLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();

        txtLog.setEditable(false);
        spTextLog.setViewportView(txtLog);

        btnClear.setMnemonic('C');

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTextLog, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTextLog, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JScrollPane spTextLog;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}