/*
 * PropertiesPanel.java
 *
 * Created on 3 de mayo de 2008, 11:51
 */
package org.joing.sysmon;

import java.util.Enumeration;
import java.util.Properties;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Note: This class has package scope, to be instantiated only by SystemMonitor.
 *
 * @author  Francisco Morero Peyrona
 */
public class PropertiesPanel extends javax.swing.JPanel
{
    /** Creates new form PropertiesPanel */
    public PropertiesPanel()
    {
        initComponents();
        
        String[]   asTitle = { "Property", "Value" };
        Properties pp      = System.getProperties();
        String[][] aProp   = new String[pp.size()][2];
        int        n       = 0;

        for( Enumeration e = pp.propertyNames(); e.hasMoreElements(); )
        {
            aProp[n][0] = (String) e.nextElement();
            aProp[n][1] = pp.getProperty( aProp[n][0] );
            n++;
        }

        tblProperties.setModel( new DefaultTableModel( aProp, asTitle ) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        tblProperties = new javax.swing.JTable();

        tblProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTable.setViewportView(tblProperties);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable tblProperties;
    // End of variables declaration//GEN-END:variables
}
