/*
 * TinyExplorer.java
 *
 * Created on 1 de julio de 2008, 21:06
 */
package org.joing.tinyexplorer;

import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import org.joing.common.desktopAPI.DeskComponent;
import org.joing.common.desktopAPI.DesktopManager;
import org.joing.common.desktopAPI.pane.DeskFrame;

/**
 *
 * @author  fmorero
 */
public class TinyExplorer extends javax.swing.JPanel implements DeskComponent
{
    private Tree  tree;
    private Table table;
    
    //------------------------------------------------------------------------//
    
    public TinyExplorer()
    {
        initComponents();
        
        tree  = new Tree();
        table = new Table();
        
        JScrollPane scTree = new JScrollPane();
                    scTree.getViewport().add( tree );
        
        JScrollPane scTable = new JScrollPane();
                    scTable.getViewport().add( table );
                    
        split.setLeftComponent( scTree );
        split.setRightComponent( scTable );
        
        showInFrame();
    }
    
    //------------------------------------------------------------------------//
    
    private void showInFrame()
    {
        DesktopManager dm   = org.joing.jvmm.RuntimeFactory.getPlatform().getDesktopManager();
        ImageIcon      icon = new ImageIcon( getClass().getResource( "tiny_explorer.png" ) );
        
        if( dm == null )
        {
            javax.swing.JFrame frame = new javax.swing.JFrame();
                               frame.setDefaultCloseOperation( javax.swing.JFrame.EXIT_ON_CLOSE );
                               frame.add( this );
                               frame.pack();
                               frame.setVisible( true );
        }
        else
        {
            // Show this panel in a frame created by DesktopManager Runtime.
            DeskFrame frame = dm.getRuntime().createFrame();
                      frame.setTitle( "Tiny File Explorer" );
                      frame.setIcon( icon.getImage() );
                      frame.add( (DeskComponent) this );
                      
            dm.getDesktop().getActiveWorkArea().add( frame );
        }
    }
    
    //------------------------------------------------------------------------//
    
    public static void main( String[] asArg )
    {
        new TinyExplorer();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        pnlBreadcrumb = new javax.swing.JPanel();
        btnReload = new javax.swing.JButton();

        pnlBreadcrumb.setBackground(new java.awt.Color(203, 136, 68));

        javax.swing.GroupLayout pnlBreadcrumbLayout = new javax.swing.GroupLayout(pnlBreadcrumb);
        pnlBreadcrumb.setLayout(pnlBreadcrumbLayout);
        pnlBreadcrumbLayout.setHorizontalGroup(
            pnlBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        pnlBreadcrumbLayout.setVerticalGroup(
            pnlBreadcrumbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/joing/tinyexplorer/reload.png"))); // NOI18N
        btnReload.setToolTipText("Reload");
        btnReload.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBreadcrumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(split, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlBreadcrumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(split, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReload;
    private javax.swing.JPanel pnlBreadcrumb;
    private javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables
}
