/*
 * ProxyConfig.java
 *
 * Created on 5 de noviembre de 2007, 20:10
 */

package org.joing.pde.misce.apps;

import java.net.Authenticator;
import java.net.PasswordAuthentication;
import javax.swing.ImageIcon;
import org.joing.pde.desktop.container.PDEFrame;
import org.joing.pde.runtime.PDERuntime;

/**
 *
 * @author  fmorero
 */
public class ProxyConfig extends PDEFrame
{ // TODO: Mirar aquí: http://java.sun.com/j2se/1.5.0/docs/guide/net/properties.html
    /** Creates new form ProxyConfig */
    public ProxyConfig()
    {
        initComponents();
        initComponentsValues();
        
        radGroup.add( radDirect );
        radGroup.add( radProxy  );
        
        setFrameIcon( getIcon( 20, 20 ) );
    }
    
    public static ImageIcon getIcon( int nWidth, int nHeight )
    {
        return PDERuntime.getRuntime().getIcon( ProxyConfig.class, "proxy.png", nWidth, nHeight );
    }
    
    //------------------------------------------------------------------------//
    
    private void initComponentsValues()
    {
        String sHttpHost = (String) System.getProperties().get( "http.proxyHost" );
        String sHttpPort = (String) System.getProperties().get( "http.proxyPort" );
        String sHttpExcl = (String) System.getProperties().get( "http.nonProxyHosts" );
        
        txtHttpHost.setText( sHttpHost );
        txtHttpPort.setText( sHttpPort );
        txtHttpExclude.setText( sHttpExcl );
        
        String sFtpHost = (String) System.getProperties().get( "ftp.proxyHost" );
        String sFtpPort = (String) System.getProperties().get( "ftp.proxyPort" );
        String sFtpExcl = (String) System.getProperties().get( "ftp.nonProxyHosts" );
        
        txtFtpHost.setText( sFtpHost );
        txtFtpPort.setText( sFtpPort );
        txtFtpExclude.setText( sFtpExcl );
        
        if( (sHttpHost != null && sHttpHost.length() > 0) || 
            (sHttpPort != null && sHttpPort.length() > 0) ||
            (sHttpExcl != null && sHttpExcl.length() > 0) || 
            (sFtpHost  != null && sFtpHost.length()  > 0) || 
            (sFtpPort  != null && sFtpPort.length()  > 0) ||
            (sFtpExcl  != null && sFtpExcl.length()  > 0) )
            radProxy.setSelected( true );
        else
            radDirect.setSelected( true );
    }
    
    private void setProxySettings()
    {
        System.getProperties().remove( "http.proxyHost"     );
        System.getProperties().remove( "http.proxyPort"     );
        System.getProperties().remove( "http.nonProxyHosts" );

        System.getProperties().remove( "ftp.proxyHost"     );
        System.getProperties().remove( "ftp.proxyPort"     );
        System.getProperties().remove( "ftp.nonProxyHosts" );
        
        Authenticator.setDefault( null );

        if( radProxy.isSelected() )
        {
            System.getProperties().put( "http.proxyHost", txtHttpHost.getText().trim() );
            System.getProperties().put( "http.proxyPort", txtHttpPort.getText().trim() );
            
            if( txtHttpExclude.getText().trim().length() > 0 )
                System.getProperties().put( "http.nonProxyHosts", txtHttpExclude.getText().trim() );
            
            System.getProperties().put( "ftp.proxyHost", txtFtpHost.getText().trim() );
            System.getProperties().put( "ftp.proxyPort", txtFtpPort.getText().trim() );
            
            if( txtFtpExclude.getText().trim().length() > 0 )
                System.getProperties().put( "ftp.nonProxyHosts", txtFtpExclude.getText().trim() );
         
            if( txtUser.getText().trim().length() > 0 )
            {
                String sUser = txtUser.getText().trim();
                String sPass = String.valueOf(txtPassword.getPassword());   // No trim in passwords
                Authenticator.setDefault( new TheAuthenticator( sUser, sPass ) );
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        radGroup = new javax.swing.ButtonGroup();
        radDirect = new javax.swing.JRadioButton();
        radProxy = new javax.swing.JRadioButton();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pnlHTTP = new javax.swing.JPanel();
        lblHttpHost = new javax.swing.JLabel();
        lblHttpPort = new javax.swing.JLabel();
        txtHttpHost = new javax.swing.JTextField();
        lblHttpExclude = new javax.swing.JLabel();
        txtHttpExclude = new javax.swing.JTextField();
        txtHttpPort = new javax.swing.JTextField();
        pnlFTP = new javax.swing.JPanel();
        lblFtpHost = new javax.swing.JLabel();
        lblFtpPort = new javax.swing.JLabel();
        txtFtpHost = new javax.swing.JTextField();
        lblFtpExclude = new javax.swing.JLabel();
        txtFtpExclude = new javax.swing.JTextField();
        txtFtpPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proxy Configuration");

        radDirect.setText("Direct connection to Internet");
        radDirect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radDirectActionPerformed(evt);
            }
        });

        radProxy.setText("Proxy connection to Internet");
        radProxy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radProxyActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept");
        btnAccept.setToolTipText("zxcvb");
        btnAccept.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAcceptActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        lblUser.setText("User");

        lblPassword.setText("Password");

        pnlHTTP.setBorder(javax.swing.BorderFactory.createTitledBorder(" HTTP "));

        lblHttpHost.setText("Host");

        lblHttpPort.setText("Port");

        lblHttpExclude.setText("Exclude");

        javax.swing.GroupLayout pnlHTTPLayout = new javax.swing.GroupLayout(pnlHTTP);
        pnlHTTP.setLayout(pnlHTTPLayout);
        pnlHTTPLayout.setHorizontalGroup(
            pnlHTTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHTTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHTTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHTTPLayout.createSequentialGroup()
                        .addComponent(lblHttpHost)
                        .addGap(28, 28, 28)
                        .addComponent(txtHttpHost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblHttpPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHttpPort, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHTTPLayout.createSequentialGroup()
                        .addComponent(lblHttpExclude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHttpExclude, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHTTPLayout.setVerticalGroup(
            pnlHTTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHTTPLayout.createSequentialGroup()
                .addGroup(pnlHTTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(lblHttpHost)
                    .addComponent(txtHttpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHttpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHttpPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHTTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHttpExclude)
                    .addComponent(txtHttpExclude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlFTP.setBorder(javax.swing.BorderFactory.createTitledBorder(" FTP"));

        lblFtpHost.setText("Host");

        lblFtpPort.setText("Port");

        lblFtpExclude.setText("Exclude");

        javax.swing.GroupLayout pnlFTPLayout = new javax.swing.GroupLayout(pnlFTP);
        pnlFTP.setLayout(pnlFTPLayout);
        pnlFTPLayout.setHorizontalGroup(
            pnlFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFTPLayout.createSequentialGroup()
                        .addComponent(lblFtpHost)
                        .addGap(28, 28, 28)
                        .addComponent(txtFtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(lblFtpPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFTPLayout.createSequentialGroup()
                        .addComponent(lblFtpExclude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFtpExclude, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFTPLayout.setVerticalGroup(
            pnlFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFTPLayout.createSequentialGroup()
                .addGroup(pnlFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFtpHost)
                    .addComponent(txtFtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFtpPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFtpExclude)
                    .addComponent(txtFtpExclude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radDirect)
                    .addComponent(radProxy))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(179, 179, 179))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlHTTP, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlFTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radDirect)
                .addGap(18, 18, 18)
                .addComponent(radProxy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHTTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAccept))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radDirectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radDirectActionPerformed
    {//GEN-HEADEREND:event_radDirectActionPerformed
        // TODO: Deshabilitar los controles del Proxy
    }//GEN-LAST:event_radDirectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAcceptActionPerformed
    {//GEN-HEADEREND:event_btnAcceptActionPerformed
        setProxySettings();
        dispose();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void radProxyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radProxyActionPerformed
    {//GEN-HEADEREND:event_radProxyActionPerformed
        // TODO: Habilitar los controles del Proxy
    }//GEN-LAST:event_radProxyActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ProxyConfig().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblFtpExclude;
    private javax.swing.JLabel lblFtpHost;
    private javax.swing.JLabel lblFtpPort;
    private javax.swing.JLabel lblHttpExclude;
    private javax.swing.JLabel lblHttpHost;
    private javax.swing.JLabel lblHttpPort;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlFTP;
    private javax.swing.JPanel pnlHTTP;
    private javax.swing.JRadioButton radDirect;
    private javax.swing.ButtonGroup radGroup;
    private javax.swing.JRadioButton radProxy;
    private javax.swing.JTextField txtFtpExclude;
    private javax.swing.JTextField txtFtpHost;
    private javax.swing.JTextField txtFtpPort;
    private javax.swing.JTextField txtHttpExclude;
    private javax.swing.JTextField txtHttpHost;
    private javax.swing.JTextField txtHttpPort;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
 
     
   //-------------------------------------------------------------------------//
   // INNER CLASS: MyAuthenticator
   //-------------------------------------------------------------------------//
   private final static class TheAuthenticator extends Authenticator
   {
      private final PasswordAuthentication pa;

      public TheAuthenticator( String sUser, String sPassword )
      {
         this.pa = new PasswordAuthentication( sUser, sPassword.toCharArray() );
      }

      protected PasswordAuthentication getPasswordAuthentication()
      {
         return this.pa;
      }
   }
}