/*
 * LoginPanel.java
 *
 * Created on 30 de junio de 2007, 05:41 PM
 */

package org.joing.desktop.login;

/**
 *
 * @author  Mario Serrano
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private LoginListener loginListener;
    
    /** Creates new form LoginPanel */
    public LoginPanel() {
        initComponents();
    }

    public void setLoginListener(LoginListener loginListener) {
        this.loginListener = loginListener;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbInicio = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tfUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(313, 213));
        setLayout(null);

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbUser.setForeground(new java.awt.Color(51, 51, 51));
        lbUser.setText("Usuario:");
        add(lbUser);
        lbUser.setBounds(50, 82, 46, 14);

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbPassword.setForeground(new java.awt.Color(51, 51, 51));
        lbPassword.setText("Password:");
        add(lbPassword);
        lbPassword.setBounds(50, 120, 57, 14);

        lbInicio.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbInicio.setForeground(new java.awt.Color(153, 153, 153));
        lbInicio.setText("Inicio de Sesion");
        add(lbInicio);
        lbInicio.setBounds(20, 20, 96, 15);

        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setBorder(null);
        tfPassword.setOpaque(false);
        add(tfPassword);
        tfPassword.setBounds(120, 115, 160, 20);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setOpaque(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(187, 150, 90, 20);

        tfUser.setFont(new java.awt.Font("Tahoma", 1, 11));
        tfUser.setForeground(new java.awt.Color(0, 51, 153));
        tfUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUser.setBorder(null);
        tfUser.setOpaque(false);
        add(tfUser);
        tfUser.setBounds(120, 80, 160, 20);
        add(jSeparator1);
        jSeparator1.setBounds(20, 40, 270, 3);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/joing/desktop/login/resources/Login.png"))); // NOI18N
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(loginListener!=null){
            String username = tfUser.getText().trim();
            String password = new String(tfPassword.getPassword()).trim();
            loginListener.onLogin(username,password);
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
    
}
