/*
 * JErrorPanel.java
 *
 * Created on 5 de julio de 2008, 19:00
 */

package org.joing.swingtools;

import java.awt.Image;
import java.awt.Window;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import org.joing.common.desktopAPI.DeskComponent;
import org.joing.common.desktopAPI.StandardImage;

/**
 *
 * @author  fmorero
 */
public class JErrorPanel extends javax.swing.JPanel implements DeskComponent
{
    /** Creates new form JErrorPanel */
    public JErrorPanel()
    {
        this( null );
    }
    
    public JErrorPanel( Throwable exc )
    {
        if( exc == null )
            exc = new IllegalArgumentException( "Passed exception to constructor can't be null." );
        
        initComponents();
        
        Image image = org.joing.jvmm.RuntimeFactory.getPlatform().getDesktopManager().getRuntime().getImage( StandardImage.ALERT, 50, 50 );
        
        lblIcon.setIcon( new ImageIcon( image ) );
        txtMessage.setText( exc.toString() );
        
        StringBuffer        sb     = new StringBuffer( 1024 );
        StackTraceElement[] aStack = exc.getStackTrace();
        
        for( int n = 0; n < aStack.length; n++ )
            sb.append( aStack[n].toString() ).append( '\n' );
        
        txtStackTrace.setText( sb.toString() );
        txtStackTrace.setCaretPosition( 0 );
        onDetails( null );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        spStackTrace = new javax.swing.JScrollPane();
        txtStackTrace = new javax.swing.JTextArea();
        spMessage = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnDetails = new javax.swing.JButton();

        txtStackTrace.setColumns(20);
        txtStackTrace.setRows(5);
        spStackTrace.setViewportView(txtStackTrace);

        spMessage.setBorder(null);
        spMessage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spMessage.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        spMessage.setOpaque(false);

        txtMessage.setColumns(20);
        txtMessage.setEditable(false);
        txtMessage.setFont(txtMessage.getFont().deriveFont(txtMessage.getFont().getStyle() | java.awt.Font.BOLD));
        txtMessage.setLineWrap(true);
        txtMessage.setRows(5);
        txtMessage.setText("Message");
        txtMessage.setWrapStyleWord(true);
        txtMessage.setBorder(null);
        txtMessage.setOpaque(false);
        spMessage.setViewportView(txtMessage);

        btnDetails.setText("Details ");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDetails(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spStackTrace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                    .addComponent(btnDetails))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spMessage, 0, 0, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spStackTrace, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void onDetails(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDetails
    String sText = btnDetails.getText();
           sText = sText.substring( 0, sText.indexOf( ' ' ) + 1 );    // Gets the "Details " part (one thing less for i18n)
           
    spStackTrace.setVisible( ! spStackTrace.isVisible() );
    btnDetails.setText( sText + (spStackTrace.isVisible() ? "<<" : ">>") );
    getLayout().layoutContainer( this );
    
    // Now we do our best to find window parent (to invoke pack() on it)
    Window window = (Window) SwingUtilities.getAncestorOfClass( Window.class, this );
    
    if( window != null )
    {
        window.pack();
    }
    else
    {
        JInternalFrame iframe = (JInternalFrame) SwingUtilities.getAncestorOfClass( JInternalFrame.class, this );
        
        if( iframe != null)
            iframe.pack();
    }
}//GEN-LAST:event_onDetails

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JScrollPane spMessage;
    private javax.swing.JScrollPane spStackTrace;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtStackTrace;
    // End of variables declaration//GEN-END:variables
}