/*
 * PDEBaseAboutPanel.java
 *
 * Created on 22 de abril de 2008, 9:42
 */
package org.joing.pde.swing;

import org.joing.common.Constant;

/**
 *
 * @author  fmorero
 */
public class PDEAboutPanel extends javax.swing.JPanel
{
    /** Creates new form PDEBaseAboutPanel */
    public PDEAboutPanel()
    {
        initComponents();
        
        lblVersion.setText( "Version "+ Constant.getVersion() );
    }

    public String getCopyright()
    {
        return lblCopyright.getText();
    }

    public void setCopyright( String sCopyright )
    {
       this.lblCopyright.setText( sCopyright );
    }

    public String getProductName()
    {
        return lblName.getText();
    }

    public void setProductName( String sName )
    {
        this.lblName.setText( sName );
    }

    public String getVersion()
    {
        return lblVersion.getText();
    }

    public void setVersion( String sVersion )
    {
        this.lblVersion.setText( sVersion );
    }

    public String getDescription()
    {
        return txtDescription.getText();
    }

    public void setDescription( String sDescription )
    {
        this.txtDescription.setText( sDescription );
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblHomePage = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblCopyright1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/joing/pde/misce/images/pde.png"))); // NOI18N
        lblImage.setBorder(null);

        lblName.setFont(lblName.getFont().deriveFont((float)28));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");

        lblVersion.setFont(lblVersion.getFont().deriveFont((float)22));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("Version");
        lblVersion.setBorder(null);

        lblHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomePage.setText("Author: Francisco Morero Peyrona");

        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("This piece is part of Peyrona Desktop Environment");

        spDescription.setOpaque(false);

        txtDescription.setColumns(20);
        txtDescription.setEditable(false);
        txtDescription.setRows(5);
        txtDescription.setText("Description");
        txtDescription.setWrapStyleWord(true);
        txtDescription.setOpaque(false);
        spDescription.setViewportView(txtDescription);

        lblCopyright1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright1.setText("http://www.joing.org");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("© Join'g Team - Published under GPLv3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHomePage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblImage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                    .addComponent(spDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(lblCopyright1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(lblCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVersion))
                    .addComponent(lblImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCopyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCopyright1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomePage)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblCopyright1;
    private javax.swing.JLabel lblHomePage;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}