/*
 * VFSPanel.java
 *
 * Created on 2 de agosto de 2007, 18:21
 */

package org.joing.vfs;

/**
 *
 * @author  fmorero
 */
public class VFSPanel extends javax.swing.JPanel
{
    private FileTreePanel pnlFileTree;
    
    /** Creates new form VFSPanel */
    public VFSPanel()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUpload = new javax.swing.JTextField();
        btnUpExplore = new javax.swing.JButton();
        txtDownload = new javax.swing.JTextField();
        btnDownExplore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpOk = new javax.swing.JButton();
        btnDownOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spTree = new javax.swing.JScrollPane();
        btnConnect = new javax.swing.JButton();

        jLabel1.setText("Virtual File System");

        jLabel2.setText("Upload");

        btnUpExplore.setText("...");
        btnUpExplore.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnUpExplore.setMaximumSize(new java.awt.Dimension(19, 19));
        btnUpExplore.setMinimumSize(new java.awt.Dimension(19, 19));
        btnUpExplore.setPreferredSize(new java.awt.Dimension(19, 19));

        btnDownExplore.setText("...");
        btnDownExplore.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDownExplore.setMaximumSize(new java.awt.Dimension(19, 19));
        btnDownExplore.setMinimumSize(new java.awt.Dimension(19, 19));
        btnDownExplore.setPreferredSize(new java.awt.Dimension(19, 19));

        jLabel3.setText("Download");

        jLabel4.setText("Selected directory");

        btnUpOk.setText("Ok");
        btnUpOk.setMargin(new java.awt.Insets(3, 2, 3, 2));

        btnDownOk.setText("Ok");
        btnDownOk.setMargin(new java.awt.Insets(3, 2, 3, 2));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 9));
        jLabel5.setText("(right click on file to get popup)");

        btnConnect.setText("Connect");
        btnConnect.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnConnect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spTree, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDownload)
                                    .addComponent(txtUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDownExplore, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpExplore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDownOk, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(btnUpOk, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                            .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnConnect))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(txtUpload)
                    .addComponent(btnUpExplore, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpOk, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(txtDownload)
                    .addComponent(btnDownExplore, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownOk, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTree, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConnectActionPerformed
    {//GEN-HEADEREND:event_btnConnectActionPerformed
        pnlFileTree = new FileTreePanel();
        spTree.setViewportView( pnlFileTree );
    }//GEN-LAST:event_btnConnectActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDownExplore;
    private javax.swing.JButton btnDownOk;
    private javax.swing.JButton btnUpExplore;
    private javax.swing.JButton btnUpOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane spTree;
    private javax.swing.JTextField txtDownload;
    private javax.swing.JTextField txtUpload;
    // End of variables declaration//GEN-END:variables
}