/*
 * JVFSPropertiesPanel.java
 *
 * Created on 14 de agosto de 2008, 9:13
 */
package org.joing.swingtools.filesystem;

import javax.swing.SwingUtilities;
import org.joing.common.desktopAPI.DeskComponent;
import org.joing.common.dto.vfs.FileDescriptor;

/**
 *
 * @author  fmorero
 */
public class JVFSPropertiesPanel extends javax.swing.JPanel implements DeskComponent
{
    private FileDescriptor fd;
    
    /** Creates new form JVFSPropertiesPanel */
    public JVFSPropertiesPanel()
    {
        this( null );
    }
    
    public JVFSPropertiesPanel( FileDescriptor fd )
    {
        initComponents();
        if( fd != null )
            setFileDesCriptor( fd );
    }
    
    public void setFileDesCriptor( FileDescriptor descriptor )
    {
        this.fd = descriptor;
        
        SwingUtilities.invokeLater( new Runnable()
        {
            public void run()
            {
                String sPath = fd.getAbsolutePath();
                       sPath = sPath.substring( 0, sPath.length() - fd.getName().length() );
                       
                txtName.setText( fd.getName() );
                txtPath.setText( sPath );
                txtAccount.setText( fd.getAccount() );
                txtOwner.setText( fd.getOwner() );
                
                chkDirectory.setSelected( fd.isDirectory() );
                chkHidden.setSelected( fd.isHidden() );
                chkPublic.setSelected( fd.isPublic() );
                chkInTrashcan.setSelected( fd.isInTrashcan() );
                chkExecutable.setSelected( fd.isExecutable() );
                chkReadable.setSelected( fd.isReadable() );
                chkModifiable.setSelected( fd.isModifiable() );
                chkDeleteable.setSelected( fd.isDeleteable() );
                chkAlterable.setSelected( fd.isAlterable() );
                chkDuplicable.setSelected( fd.isDuplicable() );
                
                txtCreated.setText( fd.getCreated().toString() );
                txtModified.setText( fd.getModified().toString() );
                txtAccessed.setText( fd.getAccessed().toString() );
                txtSize.setText( fd.getSize() +" bytes" );
                
                txtNotes.setText( fd.getNotes() );
            }
        } );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAccount = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        lblOwner = new javax.swing.JLabel();
        txtOwner = new javax.swing.JTextField();
        chkDirectory = new javax.swing.JCheckBox();
        chkReadable = new javax.swing.JCheckBox();
        chkHidden = new javax.swing.JCheckBox();
        chkPublic = new javax.swing.JCheckBox();
        chkInTrashcan = new javax.swing.JCheckBox();
        chkExecutable = new javax.swing.JCheckBox();
        chkModifiable = new javax.swing.JCheckBox();
        chkDeleteable = new javax.swing.JCheckBox();
        chkAlterable = new javax.swing.JCheckBox();
        chkDuplicable = new javax.swing.JCheckBox();
        lblCreated = new javax.swing.JLabel();
        txtCreated = new javax.swing.JTextField();
        lblModified = new javax.swing.JLabel();
        txtModified = new javax.swing.JTextField();
        lblAccessed = new javax.swing.JLabel();
        txtAccessed = new javax.swing.JTextField();
        lblSize = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        spNote = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        lblNotes = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        lblName.setText("Name");

        lblAccount.setText("Account");

        txtAccount.setEditable(false);

        lblPath.setText("Path");

        txtPath.setEditable(false);

        lblOwner.setText("Owner");

        chkDirectory.setText("Directory");
        chkDirectory.setEnabled(false);

        chkReadable.setText("Readable");

        chkHidden.setText("Hidden");

        chkPublic.setText("Public");

        chkInTrashcan.setText("InTrashcan");

        chkExecutable.setText("Executable");

        chkModifiable.setText("Modifiable");

        chkDeleteable.setText("Deleteable");

        chkAlterable.setText("Alterable");

        chkDuplicable.setText("Duplicable");

        lblCreated.setText("Created");

        txtCreated.setEditable(false);

        lblModified.setText("Modified");

        txtModified.setEditable(false);

        lblAccessed.setText("Accessed");

        lblSize.setText("Size");

        txtSize.setEditable(false);

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        spNote.setViewportView(txtNotes);

        lblNotes.setText("Notes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spNote, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblPath)
                            .addComponent(lblOwner)
                            .addComponent(lblAccount))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkExecutable)
                                    .addComponent(chkInTrashcan)
                                    .addComponent(chkPublic)
                                    .addComponent(chkHidden)
                                    .addComponent(chkDirectory))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkDeleteable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkModifiable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkAlterable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkDuplicable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkReadable)))
                            .addComponent(txtOwner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreated)
                            .addComponent(lblModified)
                            .addComponent(lblAccessed))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModified, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtAccessed, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtCreated, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addComponent(lblSize)
                    .addComponent(lblNotes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPath)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccount)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOwner)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(chkHidden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkPublic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkInTrashcan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkExecutable))
                            .addComponent(chkDirectory))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCreated)
                            .addComponent(txtCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModified)
                            .addComponent(txtModified, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccessed)
                            .addComponent(txtAccessed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSize)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkReadable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkModifiable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDeleteable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAlterable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDuplicable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spNote)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAlterable;
    private javax.swing.JCheckBox chkDeleteable;
    private javax.swing.JCheckBox chkDirectory;
    private javax.swing.JCheckBox chkDuplicable;
    private javax.swing.JCheckBox chkExecutable;
    private javax.swing.JCheckBox chkHidden;
    private javax.swing.JCheckBox chkInTrashcan;
    private javax.swing.JCheckBox chkModifiable;
    private javax.swing.JCheckBox chkPublic;
    private javax.swing.JCheckBox chkReadable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAccessed;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblModified;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblSize;
    private javax.swing.JScrollPane spNote;
    private javax.swing.JTextField txtAccessed;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtCreated;
    private javax.swing.JTextField txtModified;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtOwner;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
